# permissions for end users to view bpfdns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bpfdns-viewer-role
rules:
- apiGroups:
  - bpfdns.bpf.dns
  resources:
  - bpfdns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bpfdns.bpf.dns
  resources:
  - bpfdns/status
  verbs:
  - get
