
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - bpfdns.bpf.dns
  resources:
  - bpfdns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - bpfdns.bpf.dns
  resources:
  - bpfdns/finalizers
  verbs:
  - update
- apiGroups:
  - bpfdns.bpf.dns
  resources:
  - bpfdns/status
  verbs:
  - get
  - patch
  - update
