apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
    app.kubernetes.io/component: test
    app.kubernetes.io/instance: test
  name: test
  
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: test
    spec:
      containers:
      - args:
        - "1000"
        command:
        - sleep
        env:
        - name: BPF_IFACE
          value: ens192
        image: quay.io/valeube/basic_firewall
        imagePullPolicy: IfNotPresent
        name: test
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      hostNetwork: true
      hostPID: true
      priority: 0
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsUser: 0
      serviceAccount: superman
      serviceAccountName: superman
      terminationGracePeriodSeconds: 30
